---
title: "Data Management Glossary"
format: gfm
editor: visual
---

## Organizations

- CRKN
- Digital Research Alliance of Canada
- DataCite Canada Consortium
- Borealis
- CrossRef
- LAC
- CPIDAC
- Statistics Canada - For a final project it may be interesting to implement government data such as census data offered by Statistics Canada.

## Persistent Identifiers

- PID
- ORCID
- DOI
- ISSN

## Concepts

- Open Access
- Open Source
- Metadata
- License (as a verb, providing access to ejournals, databases, etc)
- Creative Commons License
- Trustworthy Digital Repository (TDR)
- COUNTER usage statistics
- Peer review
- SAFES Data
- FAIR Principles
- CARE Principles
- Data repository - Data repositories have different uses, they are a place where data can be held, where is can be used, and a place where data can be organized in an appropriate manner. It can also serve as a place where researchers can organize and submit their data in a location that is specific to their subject of research. Source: <https://datamanagement.hms.harvard.edu/about/data-management-terminology>
